language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '10'
branches:
  except:
    - /^v\d+\.\d+\.\d+$/

jobs:
  include:
    - stage: test
      script: npm run test:prod && npm run build
    - stage: deploy
      script: npm run build && npm run semantic-release
      if: branch = master
