language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '10'
branches:
  except:
    - /^v\d+\.\d+\.\d+$/

jobs:
  include:
    - stage: test
      script: npm run test:prod && npm run build
    - stage: deploy
      script: if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then npm run semantic-release; fi
